index: home.ejs
pages:
  login: login.ejs
  store: store.ejs
  servers/create: create.ejs
  earn: earn.ejs
  lv: lv.ejs
  j4r: j4r.ejs
  referrals: referrals.ejs
  notfound: 404.ejs
  admin: admin/admin.ejs
  admin/coins: admin/coins.ejs
  admin/users: admin/users.ejs
  admin/coupon: admin/coupon.ejs
  admin/package: admin/package.ejs

redirects: 
  callback: /home
  invalid_amount: /store?error=INVALID_AMOUNT
  cant_afford: /store?error=CANT_AFFORD
  store_error: /store?error=AN_ERROR_OCCURED
  store_sucess: /store?sucess=true
  password_reset: /login?reset=sucess
  missing_info: /store?error=MISSING_INFO

mustbeloggedin: 
  - /
  - /store
  - /servers/create
  - /earn
  - /lv
  - /j4r
  - /referrals

mustbeadmin:
  - /admin
  - /admin/coins
  - /admin/users
  - /admin/coupon
  - /admin/package

  
